// The Old Monk playlist. Add or remove tracks here — nothing else needs to change.
//
// `youtubeId` is the only required field for playback (it's fed straight into
// the hidden YouTube player). Everything else is display metadata.
// `cover` is optional — when omitted, the YouTube thumbnail for `youtubeId` is used.

export type Track = {
  youtubeId: string;
  title: string;
  artist: string;
  album?: string;
  cover?: string;
};

export const tracks: Track[] = [
  {
    youtubeId: "Q_cq8__k--M",
    title: "Barsaat Ke Mausam Mein",
    artist: "Kumar Sanu, Roop Kumar Rathod",
    album: "Naajayaz",
  },
  {
    youtubeId: "A9mB9tEFkfA",
    title: "Log Kehte Hain Main Sharabi Hoon",
    artist: "Kishore Kumar",
    album: "Sharabi",
  },
  {
    youtubeId: "nYXmSpgphpM",
    title: "Intehaa ho gai intezaar ki",
    artist: "Kishor Kumar, Asha Bhosle",
    album: "Sharabi",
  },
  {
    youtubeId: "_D7lzzD8l6M",
    title: "So Gaya Yeh Jahan",
    artist: "Nitin Mukesh, Shabbir Kumar, Alka Yagnik",
    album: "Tezaab",
  },
  {
    youtubeId: "N0jnLZxYwYc",
    title: "Mujhse Mohabbat Ka Izhaar Karta",
    artist: "Udit Narayan, Alka Yagnik",
    album: "Hum Hain Rahi Pyar Ke",
  },
  {
    youtubeId: "3NWMK2MRqIk",
    title: "Tumsa Koi Pyaara",
    artist: "Kumar Sanu, Alka Yagnik",
    album: "Khuddar",
  },
  {
    youtubeId: "bga_0ziOOfQ",
    title: "Woh Meri Neend Mera Chain",
    artist: "Sadhana Sargam",
    album: "Hum Hain Rahi Pyar Ke",
  },
  {
    youtubeId: "oFxbBeYhLqM",
    title: "Saaton Janam Main Tere",
    artist: "Kumar Sanu, Alka Yagnik",
    album: "Dilwale",
  },
  {
    youtubeId: "CTuvMubzXpU",
    title: "Jeeta Tha Jiske Liye",
    artist: "Kumar Sanu, Alka Yagnik",
    album: "Dilwale",
  },
  {
    youtubeId: "i1IsLVz6T9Q",
    title: "Dard Karaara",
    artist: "Kumar Sanu, Sadhana Sargam",
    album: "Dum Laga Ke Haisha",
  },
  {
    youtubeId: "5y_TCKNzAMI",
    title: "Tumse Milne Ko Dil Karta Hai",
    artist: "Alka Yagnik, Kumar Sanu",
    album: "Phool Aur Kaante",
  },
  {
    youtubeId: "fBylcT-TWZw",
    title: "Ek Sanam Chahiye",
    artist: "Kumar Sanu",
    album: "Aashiqui",
  },
  {
    youtubeId: "CTNgz5gb3D8",
    title: "Tu Pyar Hai Kisi Aur Ka",
    artist: "Anuradha Paudwal, Kumar Sanu",
    album: "Dil Hai Ke Manta Nahin",
  },
  {
    youtubeId: "lFdSi01tpYM",
    title: "Sochenge Tumhe Pyar",
    artist: "Kumar Sanu",
    album: "Deewana",
  },
  {
    youtubeId: "dDR4oiyjUBA",
    title: "Raah Mein Unse Mulaqat",
    artist: "Kumar Sanu, Alka Yagnik",
    album: "Vijaypath",
  },
  {
    youtubeId: "otQmzlm-s7Q",
    title: "Main Duniya Bhula Doonga",
    artist: "Anuradha Paudwal, Kumar Sanu",
    album: "Aashiqui",
  },
  {
    youtubeId: "tPNwGuu_rQ4",
    title: "Tumhein Apna Banane Ki Kasam",
    artist: "Anuradha Paudwal, Kumar Sanu",
    album: "Sadak",
  },
  {
    youtubeId: "FsNc7I33w60",
    title: "Mera Dil Bhi Kitna Pagal Hai",
    artist: "Kumar Sanu, Alka Yagnik",
    album: "Saajan",
  },
  {
    youtubeId: "H5sheEWfsOQ",
    title: "Ek Ladki Ko Dekha Toh Aisa Laga",
    artist: "Kumar Sanu",
    album: "1942: A Love Story",
  },
  {
    youtubeId: "ZYotlBxpM3Q",
    title: "Pehla Nasha",
    artist: "Udit Narayan, Sadhana Sargam",
    album: "Jo Jeeta Wohi Sikandar",
  },
  {
    youtubeId: "KlDD9rnm3G4",
    title: "Humein Tumse Pyaar Kitna",
    artist: "Kishore Kumar, Parveen Sultana",
    album: "Kudrat",
  },
  {
    youtubeId: "mFNNKeunEeY",
    title: "Chura Liya Hai Tumne Jo Dil Ko",
    artist: "Asha Bhosle, Mohammed Rafi",
    album: "Yaadon Ki Baaraat",
  },
  {
    youtubeId: "W6dKaCV-mJQ",
    title: "Kya Hua Tera Wada",
    artist: "Mohammed Rafi",
    album: "Hum Kisise Kum Naheen",
  },
  {
    youtubeId: "Lw7RQj6SE4Q",
    title: "Aane Wala Pal",
    artist: "Kishore Kumar",
    album: "Gol Maal",
  },
  {
    youtubeId: "JQoSSJDZxOo",
    title: "Rimjhim Gire Saawan",
    artist: "Kishore Kumar",
    album: "Manzil",
  },
  {
    youtubeId: "3IY-8rcC2Fk",
    title: "O Saathi Re",
    artist: "Kishore Kumar",
    album: "Muqaddar Ka Sikandar",
  },
  {
    youtubeId: "Ypyekxaj3gw",
    title: "Yeh Shaam Mastani",
    artist: "Kishore Kumar",
    album: "Kati Patang",
  },
  {
    youtubeId: "3OfIccV3AIg",
    title: "Tere Mere Milan Ki Yeh Raina",
    artist: "Lata Mangeshkar, Kishore Kumar",
    album: "Abhimaan",
  },
  {
    youtubeId: "efx6wVOWELI",
    title: "Mere Naina Sawan Bhadon",
    artist: "Kishore Kumar",
    album: "Mehbooba",
  },
  {
    youtubeId: "Mcs2xEZ6K8o",
    title: "Dheere Dheere Se Meri Zindagi Mein Aana",
    artist: "Kumar Sanu, Anuradha Paudwal",
    album: "Aashiqui",
  },
  {
    youtubeId: "Drfqwqkm4ho",
    title: "Dil Deewana Bin Sajna Ke",
    artist: "Lata Mangeshkar, S.P. Balasubrahmanyam",
    album: "Maine Pyar Kiya",
  },
  {
    youtubeId: "otSbGQIYgpQ",
    title: "Tere Bina Zindagi Se",
    artist: "Kishore Kumar, Lata Mangeshkar",
    album: "Aandhi",
  },
  {
    youtubeId: "sPiOMuvzSI8",
    title: "Gum Hai Kisi Ke Pyar Mein",
    artist: "Kishore Kumar, Lata Mangeshkar",
    album: "Rampur Ka Lakshman",
  },
  {
    youtubeId: "q6OnRBuM788",
    title: "Kahin Deep Jale Kahin Dil",
    artist: "Lata Mangeshkar",
    album: "Bees Saal Baad",
  },
  {
    youtubeId: "u0u7QznNFFI",
    title: "Woh Sham Kuch Ajeeb Thi",
    artist: "Kishore Kumar",
    album: "Khamoshi",
  },
  {
    youtubeId: "bqbf-QiP_2U",
    title: "Zindagi Pyar Ka Geet Hai",
    artist: "Kishore Kumar",
    album: "Souten",
  },
  {
    youtubeId: "6UiwXthbtZs",
    title: "Chandi Jaisa Rang Hai Tera",
    artist: "Pankaj Udhas",
    album: "Ek Hi Maqsad",
  },
  {
    youtubeId: "tHK7f4VpJ48",
    title: "Tujhse Naraz Nahin Zindagi",
    artist: "Lata Mangeshkar",
    album: "Masoom",
  },
  {
    youtubeId: "7TOj5pAzPZU",
    title: "Jiye To Jiye Kaise",
    artist: "Kumar Sanu, S.P. Balasubrahmanyam, Anuradha Paudwal",
    album: "Saajan",
  },
  {
    youtubeId: "qrNbG2W6IRE",
    title: "Lagi Aaj Sawan Ki",
    artist: "Suresh Wadkar, Anupama Deshpande",
    album: "Chandni",
  },
  {
    youtubeId: "JkWWZZVH1tk",
    title: "Seene Mein Jalan",
    artist: "Suresh Wadkar",
    album: "Gaman",
  },
  {
    youtubeId: "r6lg5wU-AB8",
    title: "Meri Bheegi Bheegi Si",
    artist: "Kishore Kumar",
    album: "Anamika",
  },
  {
    youtubeId: "yexZf8g_dJw",
    title: "Chitthi Aai Hai",
    artist: "Pankaj Udhas",
    album: "Naam",
  },
  {
    youtubeId: "vLpRfaRiDnk",
    title: "Zindagi Ka Safar",
    artist: "Kishore Kumar",
    album: "Safar",
  },
  {
    youtubeId: "-PwDZUbHpuI",
    title: "Chingari Koi Bhadke",
    artist: "Kishore Kumar",
    album: "Amar Prem",
  },
  {
    youtubeId: "vaPDjEpk1qw",
    title: "Lambi Judaai",
    artist: "Reshma",
    album: "Hero",
  },
  {
    youtubeId: "vIQNtSQMxZA",
    title: "Kuchh To Log Kahenge",
    artist: "Kishore Kumar",
    album: "Amar Prem",
  },
  {
    youtubeId: "mTdCsH7n09c",
    title: "Aur Is Dil Mein Kya Rakhha Hai",
    artist: "Asha Bhosle, Suresh Wadkar",
    album: "Imaandar",
  },
  {
    youtubeId: "nWpbq16m0LA",
    title: "Yeh Duniya Yeh Mehfil",
    artist: "Mohammed Rafi",
    album: "Heer Ranjha",
  },
  {
    youtubeId: "GQLnC6ds44k",
    title: "Jeene Ke Liye Socha Hi Nahi",
    artist: "Anup Ghoshal",
    album: "Masoom",
  },
  {
    youtubeId: "wQFmMmBMRHE",
    title: "Sheesha Ho Ya Dil Ho",
    artist: "Lata Mangeshkar",
    album: "Aasha",
  },
  {
    youtubeId: "9rq50DlsxC4",
    title: "Yeh Jo Mohabbat Hai",
    artist: "Kishore Kumar",
    album: "Kati Patang",
  },
  {
    youtubeId: "sWqjZpBtcxc",
    title: "Aye Mere Humsafar",
    artist: "Alka Yagnik, Udit Narayan",
    album: "Qayamat Se Qayamat Tak",
  },
  {
    youtubeId: "V9Gk-69z-0o",
    title: "Dard-E-Dil Dard-E-Jigar",
    artist: "Mohammed Rafi",
    album: "Karz",
  },
  {
    youtubeId: "4pNCnlN0fo4",
    title: "Tu Mile Dil Khile",
    artist: "Kumar Sanu, Alka Yagnik",
    album: "Criminal",
  },
  {
    youtubeId: "amFnE1HPP_U",
    title: "Bahon Mein Chale Aao",
    artist: "Lata Mangeshkar",
    album: "Anamika",
  },
  {
    youtubeId: "NiVVvkUCWZo",
    title: "Dil Hai Ke Manta Nahin",
    artist: "Kumar Sanu, Anuradha Paudwal",
    album: "Dil Hai Ke Manta Nahin",
  },
  {
    youtubeId: "Kxd6po6wL4w",
    title: "Mere Rang Mein Rangne Wali",
    artist: "S.P. Balasubrahmanyam",
    album: "Maine Pyar Kiya",
  },
  {
    youtubeId: "PUUsJZ5n8pU",
    title: "Doori Na Rahe Koi",
    artist: "Lata Mangeshkar",
    album: "Kartavya",
  },
  {
    youtubeId: "agqWgqMOG6I",
    title: "Sun Sahiba Sun",
    artist: "Lata Mangeshkar",
    album: "Ram Teri Ganga Maili",
  },
  {
    youtubeId: "RfK54g1wo9k",
    title: "Kehna Hi Kya",
    artist: "K.S. Chithra",
    album: "Bombay",
  },
  {
    youtubeId: "HgYiNVNsHwE",
    title: "Gazab Ka Hai Din",
    artist: "Alka Yagnik, Udit Narayan",
    album: "Qayamat Se Qayamat Tak",
  },
  {
    youtubeId: "eKIpHujNdX0",
    title: "Do Dil Mil Rahe Hain",
    artist: "Kumar Sanu",
    album: "Pardes",
  },
  {
    youtubeId: "wr2xFauvGys",
    title: "Aankhon Ki Gustakhiyan",
    artist: "Kumar Sanu, Kavita Krishnamurthy",
    album: "Hum Dil De Chuke Sanam",
  },
  {
    youtubeId: "oEg_iXEWlt4",
    title: "Tu Meri Zindagi Hai",
    artist: "Anuradha Paudwal, Kumar Sanu",
    album: "Aashiqui",
  },
  {
    youtubeId: "NcYWrYassSw",
    title: "Pyar Karne Wale Kabhi Darte Nahin",
    artist: "Lata Mangeshkar, Manhar Udhas",
    album: "Hero",
  },
  {
    youtubeId: "cgU9eSfoZmo",
    title: "Saagar Kinare Dil Ye Pukare",
    artist: "Lata Mangeshkar, Kishore Kumar",
    album: "Saagar",
  },
  {
    youtubeId: "z-vcE-UTc-0",
    title: "Yeh Haseen Wadiyan",
    artist: "S.P. Balasubrahmanyam, K.S. Chithra",
    album: "Roja",
  },
  {
    youtubeId: "NCpvWAjdk8M",
    title: "Chitthi Na Koi Sandesh",
    artist: "Jagjit Singh",
    album: "Dushman",
  },
  {
    youtubeId: "KwiDJclWo44",
    title: "Tadap Tadap Ke",
    artist: "K.K., Kavita Krishnamurthy",
    album: "Hum Dil De Chuke Sanam",
  },
  {
    youtubeId: "rXHY4Cv9cA8",
    title: "Ab Tere Bin Jee Lenge Hum",
    artist: "Kumar Sanu",
    album: "Aashiqui",
  },
  {
    youtubeId: "joBLX7Vu5Dk",
    title: "Aye Ajnabi",
    artist: "Udit Narayan, Mahalakshmi Iyer",
    album: "Dil Se",
  },
  {
    youtubeId: "SxqyaFlB8Xw",
    title: "Sach Mere Yaar Hai",
    artist: "S.P. Balasubrahmanyam",
    album: "Saagar",
  },
  {
    youtubeId: "PynLnVnO71g",
    title: "Bahut Pyar Karte Hain Tumko Sanam",
    artist: "Anuradha Paudwal, S.P. Balasubrahmanyam",
    album: "Saajan",
  },
  {
    youtubeId: "IToz1Rq5dg4",
    title: "Yeh Kahan Aa Gaye Hum",
    artist: "Lata Mangeshkar, Amitabh Bachchan",
    album: "Silsila",
  },
  {
    youtubeId: "2aKCKAD6rlQ",
    title: "Chhookar Mere Mann Ko",
    artist: "Kishore Kumar",
    album: "Yaarana",
  },
  {
    youtubeId: "GNTNnp5rk5E",
    title: "Aane Se Uske Aaye Bahar",
    artist: "Mohammed Rafi",
    album: "Jeene Ki Raah",
  },
  {
    youtubeId: "olNJ2-h2_JA",
    title: "Neele Neele Ambar Par",
    artist: "Kishore Kumar",
    album: "Kalaakaar",
  },
  {
    youtubeId: "nU0xP9tugAQ",
    title: "Tere Dar Par Sanam",
    artist: "Kumar Sanu",
    album: "Phir Teri Kahani Yaad Aayee",
  },
  {
    youtubeId: "1Fkn3pKyFjw",
    title: "Ghar Se Nikalte Hi",
    artist: "Udit Narayan",
    album: "Papa Kehte Hain",
  },
  {
    youtubeId: "2RL0XVbs3Us",
    title: "Dil Dhoondta Hai",
    artist: "Bhupinder Singh, Lata Mangeshkar",
    album: "Mausam",
  },
];
